# docker-compose.yml
services:

  traffic:
    build: .
    container_name: 'traffic_container'
    command: >
       bash -c "python3 manage.py migrate
       && python3 manage.py collectstatic --noinput
       && python3 manage.py makesuperuser
       && python3 manage.py runserver 0.0.0.0:8000"
    ports:
      - 8020:8000
    volumes:
      - ./server:/app
      - /usr/share/nginx/html/traffic/static:/static
      - /usr/share/nginx/html/traffic/media:/media
