# Generated by Django 5.1.4 on 2024-12-07 07:33

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Позиция на карте')),
                ('direction_text', models.CharField(max_length=50)),
                ('local_video', models.FileField(upload_to='local_video')),
            ],
            options={
                'verbose_name': 'Камера',
                'verbose_name_plural': 'Камеры',
            },
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Позиция на карте')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Проблемное место',
                'verbose_name_plural': 'Проблемные места',
            },
        ),
    ]
