# Generated by Django 5.1.4 on 2024-12-07 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map_traffic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camera',
            name='point',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='point',
        ),
    ]
