# Generated by Django 5.1.4 on 2024-12-07 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_traffic', '0002_remove_camera_point_remove_problem_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='map_link',
            field=models.URLField(default='test', verbose_name='Ссылка на карту'),
            preserve_default=False,
        ),
    ]
