# Generated by Django 5.1.4 on 2024-12-07 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_traffic', '0003_camera_map_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='camera',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='map_traffic.camera'),
            preserve_default=False,
        ),
    ]
