# Generated by Django 5.1.4 on 2024-12-07 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_traffic', '0004_problem_camera'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='camera',
        ),
        migrations.AddField(
            model_name='camera',
            name='problem_place',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cameras', to='map_traffic.problem'),
            preserve_default=False,
        ),
    ]
