# Generated by Django 5.1.4 on 2024-12-07 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_traffic', '0005_remove_problem_camera_camera_problem_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camera',
            name='map_link',
        ),
        migrations.AddField(
            model_name='problem',
            name='map_link',
            field=models.URLField(default='test', verbose_name='Ссылка на карту'),
            preserve_default=False,
        ),
    ]
