# Generated by Django 5.1.4 on 2024-12-07 15:35

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_traffic', '0007_alter_problem_map_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Позиция на карте')),
                ('description', models.TextField(verbose_name='Описание проблемы')),
                ('phone', models.IntegerField(verbose_name='Номер телефона')),
                ('photo', models.FileField(upload_to='claim_photo', verbose_name='Фотография события')),
            ],
            options={
                'verbose_name': 'Заявки',
            },
        ),
        migrations.AlterField(
            model_name='camera',
            name='direction_text',
            field=models.CharField(max_length=50, verbose_name='Направление'),
        ),
        migrations.AlterField(
            model_name='camera',
            name='local_video',
            field=models.FileField(upload_to='local_video', verbose_name='Локальное видео'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
    ]
